### ISSUE TITLE
Problem with GITHUB_PAT in actions

### ISSUE THREAD

**Issue by andrewcstewart** [ropenscilabs/CIsandbox#35]
You can't actually create secrets starting with `GITHUB_`, github reserves these.  Should `GITHUB_PAT` here be updated to something else?

```
       env:
          EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
          GH_TOKEN: ${{ secrets.GITHUB_PAT }} # https://github.com/settings/tokens
          BUILD_DIR: _book/  
```
